config/routes.rb
Rails.application.routes.draw do
  resources :ds

end

app/models/d.rb
class D < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ds_controller.rb
class DsController < ApplicationController
  before_action :set_d, only: [:show, :edit, :update, :destroy]

  # GET /ds
  # GET /ds.json
  def index
    @ds = D.all
  end

  # GET /ds/1
  # GET /ds/1.json
  def show
  end

  # GET /ds/new
  def new
    @d = D.new
  end

  # GET /ds/1/edit
  def edit
  end

  # POST /ds
  # POST /ds.json
  def create
    @d = D.new(d_params)

    respond_to do |format|
      if @d.save
        format.html { redirect_to @d, notice: 'D was successfully created.' }
        format.json { render :show, status: :created, location: @d }
      else
        format.html { render :new }
        format.json { render json: @d.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ds/1
  # PATCH/PUT /ds/1.json
  def update
    respond_to do |format|
      if @d.update(d_params)
        format.html { redirect_to @d, notice: 'D was successfully updated.' }
        format.json { render :show, status: :ok, location: @d }
      else
        format.html { render :edit }
        format.json { render json: @d.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ds/1
  # DELETE /ds/1.json
  def destroy
    @d.destroy
    respond_to do |format|
      format.html { redirect_to ds_url, notice: 'D was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_d
      @d = D.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def d_params
      params.require(:d).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ds_helper.rb
module DsHelper
end

app/views/ds/_form.html.erb
<%= form_for(@d) do |f| %>
  <% if @d.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@d.errors.count, "error") %> prohibited this d from being saved:</h2>

      <ul>
      <% @d.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ds/edit.html.erb
<h1>Editing D</h1>

<%= render 'form' %>

<%= link_to 'Show', @d %> |
<%= link_to 'Back', ds_path %>

app/views/ds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ds.each do |d| %>
      <tr>
        <td><%= d.name %></td>
        <td><%= d.address %></td>
        <td><%= link_to 'Show', d %></td>
        <td><%= link_to 'Edit', edit_d_path(d) %></td>
        <td><%= link_to 'Destroy', d, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New D', new_d_path %>

app/views/ds/new.html.erb
<h1>New D</h1>

<%= render 'form' %>

<%= link_to 'Back', ds_path %>

app/views/ds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @d.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @d.address %>
</p>

<%= link_to 'Edit', edit_d_path(@d) %> |
<%= link_to 'Back', ds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobile</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>